### ISSUE TITLE
Drawing2d.fit causes pixel scale to no longer match actual pixels

### ISSUE THREAD

**Issue by MartinSStewart** [ianmackenzie/elm-2d-drawing#11]
```elm
Drawing2d.toHtml
    { viewBox = BoundingBox2d.from Point2d.origin (Point2d.xy (Pixels.pixels 100) (Pixels.pixels 100))
    , size = Drawing2d.fit
    }
    []
    [ Drawing2d.circle [] (Circle2d.atPoint Point2d.origin (Pixels.pixels 50)) ]
    |> Element.html
    |> Element.el [ Element.width <| Element.px 200, Element.height <| Element.px 200 ]
```
The following code will show the circle drawn with a 100 pixel radius instead of 50 pixels due to the viewport being 100 pixels in width and height but the canvas filling a region that is 200 pixels in width and height. To me it's misleading that you can use pixels in SVG but they don't match the size of the CSS pixels used elsewhere.

**Comment by ianmackenzie** [comment]
Yeah, this is a tricky one - any thoughts on what a fix might look like? The only thing I can really think of is just disabling `Drawing2d.fit`, but it does seem like useful functionality.

**Comment by MartinSStewart** [comment]
My feeling is that it's better to drop the pixel perfect constraint. 

Maybe instead there could be a helper function like `Drawing2d.toHtmlPixels` (yes that's a lousy placeholder name) that forces the canvas size to match the viewBox size and requires the viewBox and svg elements to use pixel units. 

The normal `Drawing2d.toHtml` could keep the same behavior it has now but not require pixel units for the viewBox and top level svg elements.

**Comment by ianmackenzie** [comment]
How about something like:

```elm
Drawing2d.fixedSize :
    Rectangle2d Pixels drawingCoordinates
    -> List (Attribute Pixels drawingCoordinates (Event Pixels drawingCoordinates msg))
    -> List (Element Pixels drawingCoordinates (Event Pixels drawingCoordinates msg))
    -> Html msg

Drawing2d.fitContainer :
    Rectangle2d drawingUnits drawingCoordinates
    -> List (Attribute drawingUnits drawingCoordinates (Event drawingUnits drawingCoordinates msg))
    -> List (Element drawingUnits drawingCoordinates (Event drawingUnits drawingCoordinates msg))
    -> Html msg

Drawing2d.fitWidth :
    Rectangle2d drawingUnits drawingCoordinates
    -> List (Attribute drawingUnits drawingCoordinates (Event drawingUnits drawingCoordinates msg))
    -> List (Element drawingUnits drawingCoordinates (Event drawingUnits drawingCoordinates msg))
    -> Html msg

{-| Pass whatever HTML/CSS attributes you want
to get some custom sizing behavior; for example,

    Drawing2d.fitContainer

is equivalent to

    Drawing2d.toHtml
        [ Html.Attributes.style "width" "100%"
        , Html.Attributes.style "height" "100%"
        ]
-}
Drawing2d.toHtml :
    List (Html.Attribute msg)
    -> Rectangle2d drawingUnits drawingCoordinates
    -> List (Attribute drawingUnits drawingCoordinates (Event drawingUnits drawingCoordinates msg))
    -> List (Element drawingUnits drawingCoordinates (Event drawingUnits drawingCoordinates msg))
    -> Html msg
```

**Comment by MartinSStewart** [comment]
So `fixedSize` locks the size of the canvas to the size of the rectangle (rotation only affects the viewbox and not the canvas), `fitContainer` causes the canvas to match the width and height of the parent container, and `fitWidth` causes the canvas to match the width of the container while the height is equal to the canvas width * viewbox aspect ratio?

**Comment by ianmackenzie** [comment]
Yup - although just to be clear, `fitContainer` wouldn't stretch/distort the image to match the container's dimensions exactly, it would maintain aspect ratio while ensuring the image fits within its container (so there will likely be some extra space either on the sides or the top and bottom).

**Comment by MartinSStewart** [comment]
So the difference between `fitContainer` and `fitWidth` is that `fitWidth` will cause the height to potentially overflow the parent container?

**Comment by ianmackenzie** [comment]
I think this can now be closed:

  - `Drawing2d.toHtml` now allows for non-pixel units to be used (but as a result requires stroke width and font size to be passed explicitly, since it's harder to choose a sensible default)
  - `Drawing2d.draw` requires pixel units and disallows scaling, and defaults to 1 pixel stroke width/16 pixel font size

@MartinSStewart would love your thoughts on the updated API!

**Comment by MartinSStewart** [comment]
The names `toHtml` and `draw` don't seem like they make their differences clear? I admit I'm not sure what I'd call them instead though.

**Comment by ianmackenzie** [comment]
Yeah, I struggled with that one a bit - I think something like `custom` would be good for `toHtml`, but I  was trying to avoid loaded words like `simple` or `basic` for `draw`.
